version: 2
jobs:
  build:
    machine: true
    environment:
      TZ: /usr/share/zoneinfo/Asia/Tokyo
    steps:
        - checkout
        - run: git config --global user.name "${GIT_USER_NAME}"
        - run: git config --global user.email "${GIT_USER_EMAIL}"

  deploy:
    docker:
      - image: circleci/golang:1.11
    working_directory: ~/blog
    environment:
      TZ: /usr/share/zoneinfo/Asia/Tokyo
    steps:
        - run: go version && go get -u github.com/gohugoio/hugo
        - checkout
        - run: sudo cp /usr/share/zoneinfo/Japan /etc/localtime
        - run: chmod +x deploy.sh && ./deploy.sh

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build 
          filters:
            branches:
              only: draft