version: 2
jobs:
  build:
    machine: true
    environment:
      TZ: /usr/share/zoneinfo/Asia/Tokyo
    steps:
        - checkout
        - run:
          command: |
            git config --global user.name "CircleCI"
            git config --global user.email "circleci@example.com"

  deploy:
    machine: true
    working_directory: ~/blog
    environment:
      TZ: /usr/share/zoneinfo/Asia/Tokyo
    steps:
        - run:
            name: install hugo
            command: go get -v github.com/gohugoio/hugo
        - checkout
        - run:
            command: |
              git config --global user.name "CircleCI"
              git config --global user.email "circleci@example.com"
              git clone https://github.com/gc373/blog.git public
              sudo cp /usr/share/zoneinfo/Japan /etc/localtime
              git submodule add -f https://github.com/gc373/blog.git public/
              git submodule sync
              git submodule update --init --recursive
              chmod +x deploy.sh && ./deploy.sh

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build 
          filters:
            branches:
              only: draft