version: 2
jobs:
  build:
    machine: true
    environment:
      TZ: /usr/share/zoneinfo/Asia/Tokyo
    steps:
        - checkout
        - run:
            command: |
              git config --global user.name "${GIT_USER_NAME}"
              git config --global user.email "${GIT_USER_EMAIL}"

  deploy:
    machine: true
    working_directory: ~/blog
    environment:
      TZ: /usr/share/zoneinfo/Asia/Tokyo
    steps:
        - run:
            name: install hugo
            command: go version && go get -u github.com/gohugoio/hugo
        - checkout
        - run:
            command: |
              sudo cp /usr/share/zoneinfo/Japan /etc/localtime
              chmod +x deploy.sh && ./deploy.sh

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build 
          filters:
            branches:
              only: draft